#!/usr/bin/env python3

import argparse
import concurrent.futures
import os
import subprocess


def current_dir():
    return os.path.dirname(os.path.abspath(__file__))


def get_dirs():
    langs = [d for d in os.listdir(current_dir())
             if os.path.isdir(d) if str.isalpha(d[0])]
    return [os.path.join(current_dir(), lang) for lang in langs]


def run_make(directory, target):
    subprocess.run(["make", target], cwd=directory)


if __name__ == "__main__":
    # コマンドライン引数の処理
    parser = argparse.ArgumentParser()
    parser.add_argument("target", help="make target", nargs="?", default="all")
    parser.add_argument("-j", help="max processes", type=int, default=1)
    args = parser.parse_args()

    # make コマンドの呼び出し
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.j) as executor:
        for d in get_dirs():
            executor.submit(run_make, d, args.target)
